### ISSUE TITLE
Inconsistent modal id type

### ISSUE THREAD

**Issue by jakobsturm** [shinokada/flowbite-svelte#4]
Hi,
I am a little bit confused about which type the modalIdStore is. It is initialized as a number (0) but the modal id is usually a string. I use typescript in my project and I receive a warning when setting the modalIdStore to a string.

See https://github.com/shinokada/flowbite-svelte/blob/af846d09b44bef789cdd2badc04a782c8c7d7408/src/lib/modals/modalStores.js#L3

I would suggest changing the default value of the store to ''

Furthermore, I am curious if you plan on adding more typescript support. There are a few further problems here and there. I am happy to help if that is something that you would like to add.

**Comment by shinokada** [comment]
Thank you again.
I will be grateful if you can help me out. 
I started this project by myself and I appreciate any help I can get.
My knowledge about typescript is limited too.
Please let me know.

**Comment by shinokada** [comment]
I just updated the modalStores.js.

Thank you.

**Comment by shinokada** [comment]
I started adding Typescript support. It's not complete but update it and let me know.

```
npm i -D flowbite-svelte@latest
```

**Comment by Gildedter** [comment]
I have a question regarding Modals, I was trying out XL-Modals yesterday and since the `id` property was optional I didn't pass it, the gotcha was my modals won't show when I click their respective buttons (inside an `each`), turns out `showModalId` wasn't the one bound, instead I had to make both `ModalButton's id and ExtraLargeModal's id the same`, is this the intended behavior?

**Comment by shinokada** [comment]
Good point. 
If you  have multiple modals in a page, without `id`, you don't know which modal to open. So I added `id`s to a modal button and modal. You can see them in action [here](https://flowbite-svelte.vercel.app/modals/all-modals).
